<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="9" passed="7" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-08-29T20:12:29 IDT" name="Default suite" finished-at="2022-08-29T20:12:35 IDT" duration-ms="5915">
    <groups>
    </groups>
    <test started-at="2022-08-29T20:12:29 IDT" name="Default test" finished-at="2022-08-29T20:12:35 IDT" duration-ms="5915">
      <class name="restassured.TestClassForFactory">
        <test-method signature="testData()[pri:0, instance:restassured.TestClassForFactory@17497425, instance params:[]]" started-at="2022-08-29T20:12:29 IDT" name="testData" finished-at="2022-08-29T20:12:33 IDT" duration-ms="3690" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testData -->
        <test-method signature="testData()[pri:0, instance:restassured.TestClassForFactory@194bcebf, instance params:[]]" started-at="2022-08-29T20:12:33 IDT" name="testData" finished-at="2022-08-29T20:12:33 IDT" duration-ms="306" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testData -->
        <test-method signature="testData()[pri:0, instance:restassured.TestClassForFactory@316bcf94, instance params:[]]" started-at="2022-08-29T20:12:33 IDT" name="testData" finished-at="2022-08-29T20:12:34 IDT" duration-ms="241" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testData -->
        <test-method signature="testData()[pri:0, instance:restassured.TestClassForFactory@3a44431a, instance params:[]]" started-at="2022-08-29T20:12:34 IDT" name="testData" finished-at="2022-08-29T20:12:34 IDT" duration-ms="283" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testData -->
        <test-method signature="testData()[pri:0, instance:restassured.TestClassForFactory@3c7f66c4, instance params:[]]" started-at="2022-08-29T20:12:34 IDT" name="testData" finished-at="2022-08-29T20:12:34 IDT" duration-ms="268" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testData -->
        <test-method signature="testData()[pri:0, instance:restassured.TestClassForFactory@4803b726, instance params:[]]" started-at="2022-08-29T20:12:34 IDT" name="testData" finished-at="2022-08-29T20:12:34 IDT" duration-ms="307" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testData -->
        <test-method signature="testData()[pri:0, instance:restassured.TestClassForFactory@53ce1329, instance params:[]]" started-at="2022-08-29T20:12:34 IDT" name="testData" finished-at="2022-08-29T20:12:35 IDT" duration-ms="230" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testData -->
        <test-method signature="testData()[pri:0, instance:restassured.TestClassForFactory@f0da945, instance params:[]]" started-at="2022-08-29T20:12:35 IDT" name="testData" finished-at="2022-08-29T20:12:35 IDT" duration-ms="245" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [404] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [404] but found [200]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1240)
at org.testng.Assert.assertEquals(Assert.java:1274)
at restassured.TestClassForFactory.testData(TestClassForFactory.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testData -->
        <test-method signature="testData()[pri:0, instance:restassured.TestClassForFactory@ffaa6af, instance params:[]]" started-at="2022-08-29T20:12:35 IDT" name="testData" finished-at="2022-08-29T20:12:35 IDT" duration-ms="230" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [404] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [404] but found [200]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1240)
at org.testng.Assert.assertEquals(Assert.java:1274)
at restassured.TestClassForFactory.testData(TestClassForFactory.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testData -->
      </class> <!-- restassured.TestClassForFactory -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
